title: Vincent Togatorop
description: A simple place for me to express my enthusiasm!
theme: just-the-docs

url: https://vincent-andreas-ct.github.io

aux_links:
  Template Repository: https://github.com/vincent-andreas-ct/vincent-andreas-ct.github.io
