title: Vincent Togatorop
description: A simple place for me to express my enthusiasm!
theme: just-the-docs

url: https://vincent-andreas-ct.github.io

aux_links:
  Template Repository: https://github.com/vincent-andreas-ct/vincent-andreas-ct.github.io

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true
